#!/bin/sh

# echo stdin to stdout.  terminate after <terminateCount> lines
USAGE="$0 [<terminateCount>]"

#set -x

TERM_COUNT=0
if [ $# -gt 0 ]; then
  TERM_COUNT=$1
  shift
fi

COUNTER=0
while read LINE; do
  echo $LINE
  # echo $0 echoing $LINE >/dev/stderr
  let COUNTER=COUNTER+1
  if [ $TERM_COUNT -gt 0 -a $COUNTER -ge $TERM_COUNT ]; then
    echo $0 TERMINATING after $LINE >/dev/stderr
    exit 1;
  fi
done